### ISSUE TITLE
Concurrency Issues: bindUntilEvent

### ISSUE THREAD

**Issue by marcelorbenites** [trello/RxLifecycle#101]
I could notice in fragments when I transform an Observable with bindUntilEvent(FragmentEvent.DESTROY_VIEW) that onNext callback gets called after onDestroyView method returns. Since I use ButterKnife and call unbind in onDestroyView I am getting NullPointerException when my onNext implementation try to access views. This behaviour does not happen all the time. Seems to be a concurrency issue. Any thoughts?

**Comment by wwwss** [comment]
How do you solve it please tell me
