### ISSUE TITLE
Using bindView (and possibly other bindings) with an Observable subscribed on an async scheduler

### ISSUE THREAD

**Issue by jnlopar** [trello/RxLifecycle#103]
`bindView` sets up its detach listener in its `OnSubscribe` call, which is nicer than the pre-1.x RxAndroid `ViewObservable.bindView` since it doesn't immediately set up the listener, even if not yet subscribed.

However, that means if I try to do (assume I'm calling this from the main thread):

```java
getNetworkThing()
    .subscribeOn(Schedulers.io())
    .compose(RxLifecycle.bindView(fooView))
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe(putThingOnViewFn);
```

it will blow up in RxBinding in its `onSubscribe` since it is being called off the main thread. One workaround is to defer, like:

```java
Observable.defer(() -> getNetworkThing().subscribeOn(Schedulers.io())) 
    .compose(...)
    ...
```

but this is clunky at best. I'm not sure we would want a hard dependency on RxAndroid and its main scheduler (I sometimes use a wrapped main thread scheduler that can run things immediately if already on the main thread anyway), but maybe we could have overloads in RxLifecycle that allow you to optionally pass in a subscribeOn scheduler for the detach stream?

```java
source.takeUntil(RxView.detaches(view).subscribeOn(scheduler))
```

seems like it would solve the problem, since the detach stream itself would subscribe on the passed in ui thread scheduler

**Comment by dlew** [comment]
We already have a hard dependency on RxAndroid via RxBinding, so that's not a problem.

I'll have to look into it but it seems reasonable to call `subscribeOn(AndroidSchedulers.mainThread())`. `RxView.detaches()` has the expectation of being run on the main thread ([see here](https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewAttachesOnSubscribe.java)).

**Comment by dlew** [comment]
So of course, after I play around with a solution, I try to verify that it works and I can't reproduce your original problem.

I tried quite a few things, but I couldn't get it to crash in the way you describe. For example, see this:

```java
Observable.create(new AsyncOnSubscribe<Integer, String>() {
    @Override
    protected Integer generateState() {
        return 0;
    }

    @Override
    protected Integer next(final Integer state, final long requested,
                           final Observer<Observable<? extends String>> observer) {
        if (state < 100) {
            observer.onNext(Observable.just("Hello, " + state));
        }
        else {
            observer.onCompleted();
        }
        return state + 1;
    }
})
    .subscribeOn(Schedulers.io())
    .compose(RxLifecycle.bindView(view))
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe(new Action1<Object>() {
        @Override
        public void call(final Object o) {
            Log.e(TAG, "Got object! " + o);
        }
    });
```

I'm calling it on the main thread - maybe your subscription isn't actually starting there?

**Comment by jnlopar** [comment]
Interesting. I was definitely seeing some crashes related to this, but it's possible one of the cases may have been off the main thread. I'll try to repro explicitly in a test though and report back.

**Comment by jnlopar** [comment]
So it turns out the ordering of `subscribeOn` is the key to getting it to blow up, at least in testing. If there is a `subscribeOn` anywhere after the `compose`, the operator lift flow will cause it to get called (and the subscription to happen)

Here are a couple options I can think of, maybe you have better ones though:

1. Leave as is but clearly document threading concerns on binding methods in RxLifecycle (which I think should happen anyway! :D )
2. Make the mainThread subscribeOn explicit on the detaches instance sent to `takeUntil`.. downsides of this are that detach subscription may be delayed, and unless we check first to see if we're already on the main thread and run it, `AndroidSchedulers` will post it to run later.
3. Make an overload with an optional subscribeOn scheduler to pass in. I kinda like this one because it would let people make a conscious decision if they were trying to start a view binding subscription off the main thread. They would know that it wasn't immediate and be able to acknowledged the downsides.
4. Slightly more out there, but, we could make `bindView` (and possibly its friends) a little bit smarter. There's another issue here, and that is that RxBinding's `detaches` isn't going to output anything if the view is already detached... so, we could `lift` to a custom operator under the hood that makes sure subscription happens on the main thread, and also makes sure that events don't get emitted if the view returns false for `isAttachedToWindow`. This all kind of begs another question though (which maybe should be a separate issue?), and that is.. what happens if you `bindView` to a view that never ends up getting attached to a window (and thus, never 'detaches')? if the source observable doesn't complete on its own, will it just keep going?
5+. ???

**Comment by jnlopar** [comment]
Actually, sorry for the thread spam, but I think there is a reasonable 5:
- Force bindView to do the attach state listener attachment synchronously when called. That would basically prevent anyone trying to subscribe it anywhere else, and also prevent a delayed subscription from setting up an attach listener after detach happens... you could even cache the detaches Observable so if the main observable subscribes after detach happens, it still gets the detach signal. the downside is of course it makes the observable have an eager side effect, and if you never subscribe from it then that is kind of wasted...

**Comment by dlew** [comment]
Did you take a look at the PR? What about that solution is problematic?

**Comment by jnlopar** [comment]
Yeah, I think that PR would work. The one place it may cause issues is if it is subscribed to off the main thread, and the post occurs after a detach happens (or if attach never happens, but that's a potential problem either way and most of the time programmer error). However, I think your pull is a good compromise. Maybe add a line to the doc of bindView recommending to call subscribe() on the main thread if they want to make sure the attach listener is set up synchronously?

**Comment by dlew** [comment]
I don't think there's any solution to the post-after-detach problem besides subscribing on the main thread.

I wonder if that means we should just let this keep crashing, since if you *do* use `subscribeOn` you're opening yourself up for subtle timing bugs. It would force people to code around this problem correctly.

**Comment by dlew** [comment]
#106 has convinced me that my PR is not the right solution because it can severely delay the incoming notifications. I think it'll be best to just put a warning on the documentation about this problem.

**Comment by dlew** [comment]
I decided to just add the warning and allow `bindView()` to continue to crash if called off the main thread. The effects of using a scheduler are too dangerous otherwise.
