### ISSUE TITLE
bindToLifecycle() issue with subscribeOn(AndroidSchedulers.mainThread())

### ISSUE THREAD

**Issue by lofei117** [trello/RxLifecycle#106]
Hi, I'm using RxLifecycle in my project, it works well on most scenes, but when I using ```bindToLifecycle``` with ```subscribeOn(AndroidSchedulers.mainThread())```, the ```Subscription#unsubscribe``` was called when the screen turns off.

I'm new to RxJava so I'm not sure whether it's a bug or not.

Below is the sample code:

```java
        RxTextView.textChanges(mSearchEditor).compose(this.<CharSequence>bindToLifecycle()).doOnUnsubscribe(new Action0() {
            @Override
            public void call() {
                // called when the screen turns off.
                Log.d("test", "unsubscribe.");
            }
        }).subscribeOn(AndroidSchedulers.mainThread()).debounce(600, TimeUnit.MILLISECONDS, AndroidSchedulers.mainThread())
                .subscribe(new Action1<CharSequence>() {
                    @Override
                    public void call(CharSequence charSequence) {
                        Log.d("test", "s:" + charSequence);
                    }
                });
```

I'll be very grateful for your help.

**Comment by dlew** [comment]
Where are you calling this code? If it's in `onResume()` then it'll unsubscribe in `onPause()`, which is expected behavior.

**Comment by lofei117** [comment]
I called the code in ```onCreateView``` for fragment, and I also tested it in ```onCreate``` for activity, both of the subscription had been unsubscribed when I turned off the screen.

**Comment by dlew** [comment]
I dug into this and found the issue. You shouldn't be calling `subscribeOn(AndroidSchedulers.mainThread())`. It's not really necessary at all. More importantly, it causes the timing of the subscription to shift until after `onResume()`, which `bindToLifecycle()` then appropriately cancels in `onPause()`.

**Comment by lofei117** [comment]
OK, thanks very much.
