### ISSUE TITLE
SupportFragment?

### ISSUE THREAD

**Issue by carmas123** [trello/RxLifecycle#108]
Hi how cai I use RxFragment with Support v4?
I cannot find RxSupportFragment class :)

**Comment by alexfu** [comment]
@carmas123 You're looking for [com.trello.rxlifecycle.components.support.RxFragment](https://github.com/trello/RxLifecycle/blob/master/rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxFragment.java)

**Comment by carmas123** [comment]
Nice, thank you
