### ISSUE TITLE
Lifecycle support 

### ISSUE THREAD

**Issue by warabei14** [trello/RxLifecycle#11]
Are there any plans to implement Android lifecycle support (recreating over rotation)?  I've seen some workarounds in the Internet, but afaiu it is some kind of the DIY LoaderManager approach. Maybe I would make pull request, if I have enough time and it is interesting to somebody but me.

**Comment by dlew** [comment]
That's not planned but it could eventually be added.

I imagine it'd have to be a store of `Observable<T>` that is stored via key and could be re-subscribed on rotation. We'd have to think a fair amount about the best API - would it be best to have it just be a dumb `HashMap`? Or should we control `subscribe()` so that we can automatically unsub/resub on rotation?

**Comment by hannesstruss** [comment]
This feels a bit too framework-y for this library.

A `HashMap` that survives config changes could be generally useful, not only to store `Observable`s. Projects like [Memento](https://github.com/mttkay/memento) already do similar things. Automatically resubscribing on the other hand maybe is a tad too much magic. It would also need additional configuration, e.g. what lifecycle event to resubscribe on, as people might have different requirements for that. 

Most people anyway have their own mechanisms in place already. I'm not sure there is a one-size-fits all solution.

**Comment by dlew** [comment]
@hannesstruss On the one hand I agree about it being very framework-y. On the other hand it *is* a common lifecycle problem people have, and this particular library is about solving common problems around the lifecycle. Plus, putting it into a library that already has to extend `Activity` and `Fragment` is a decent place for it.

I agree that automatic resub is too complex. Here's a simpler idea (though I'm very much so shooting from the hip here): 

```java
public interface ObservableLoader {

  // Must implement this to return whatever Observables desired
  <T> Observable<T> createObservable(int key);

  // Developer can use these and the Observable will be maintained on config change
  <T> Subscription subscribe(int key, Action1<T> onNext);

  <T> Subscription subscribe(int key, Action1<T> onNext, Action1<Throwable> onError);

  <T> Subscription subscribe(int key, Action1<T> onNext, Action1<Throwable> onError, Action0 onCompleted);

  // ...etc... for the other subscribe() methods

}
```

So it's not *automatic* resubscription, it's just automatic storage of `Observable<T>`. What you do with it is up to you.

**Comment by dlew** [comment]
I'm going to close this for now; I'm not convinced it's something this library (in particular) needs to solve.
