### ISSUE TITLE
Question about unsubscription

### ISSUE THREAD

**Issue by jemshit** [trello/RxLifecycle#120]
Hi.
If we have to unsubscribe all `Subscriptions` to not leak memory, and if this library does not do it (as stated in doc), what is advantage of using this? It is written lib makes `Observable` to stop emitting, but does not unsubscribe. Is not just unsubscribing from `Subscription` enough to prevent memory leak without this library (or doesn’t `.unsubscribe()` tells `Observable` to stop emitting) ?

**Comment by dlew** [comment]
Terminating the sequence is equivalent to unsubscribing for purposes of preventing memory leaks.

The docs are there to (try to) make it clear that the behavior of `RxLifecycle` is different from calling `Subscription.unsubscribe()`. When you do `unsubscribe()`, all emissions end. With `RxLifecycle` it calls a terminal event.
