### ISSUE TITLE
How can I use RxLifecycle Without appcompact V

### ISSUE THREAD

**Issue by cnisky** [trello/RxLifecycle#121]

**Comment by cnisky** [comment]
When I try to use RxLifecycle in my project, it always prompt error for not find appcompact-v7:23.3.0, I have a version of appcompact-v7:23.0.2, it is useless. See picture below.
If I can use RxLifecycle without import  appcompact-v7:23.3.0 ? 
Thanks.
![image](https://cloud.githubusercontent.com/assets/13595791/15447610/01ae9a9c-1f7b-11e6-88b4-d6e179b9888a.png)

**Comment by dlew** [comment]
You need to update your Android SDK repositories with the latest app compat/support annotations libraries.
