### ISSUE TITLE
RxView.clicks --> BUG

### ISSUE THREAD

**Issue by YougaKing** [trello/RxLifecycle#122]
When i used 
 
        RxView.clicks(mOrderInfo)
                .throttleFirst(1, TimeUnit.SECONDS)
                .subscribe(aVoid -> {
                    Intent intent = new Intent(mContext, OrderExtraActivity.class);
                    startActivity(intent);
                });

        RxView.clicks(mOrderPackage)
                .throttleFirst(1, TimeUnit.SECONDS)
                .subscribe(aVoid -> {
                    Intent intent = new Intent(mContext, OrderPackageActivity.class);
                    startActivity(intent);
                });
must two clicks

**Comment by YougaKing** [comment]
<TextView
                    android:id="@+id/order_basic"
                    style="@style/Right_EditText"
                    android:background="@drawable/white_pressed_bg"
                    android:drawableRight="@drawable/arrow"
                    android:hint="@string/not_write"/>

 RxView.clicks(mOrderBasic)
                .throttleFirst(1, TimeUnit.SECONDS)
                .subscribe(aVoid -> {
                    Intent intent = new Intent(mContext, OrderBasicActivity.class);
                    startActivity(intent);
                });

must two clicks

**Comment by dlew** [comment]
This issue seems to have nothing to do with RxLifecycle.
