### ISSUE TITLE
RxlifeCycle without using RxAppCompatActivity

### ISSUE THREAD

**Issue by krn1** [trello/RxLifecycle#123]
Is it possible to use RxLifeCycle library without using your RxAppCompatActivity or fragment ? Wiki doesn't say that I could use android framework's Activity. The sample code uses your RxAppCompatActivity. Please let me know about this .. in case if you have an example without using RxAppCompatActivity please point me there .

**Comment by dlew** [comment]
Yes, it's possible. All that [`RxLifecycle`](https://github.com/trello/RxLifecycle/blob/master/rxlifecycle/src/main/java/com/trello/rxlifecycle/RxLifecycle.java) requires is an `Observable<Event>` of some kind. If you implement your own lifecycle Observable then you can plug it in here.

One good way to do that is to implement [`ActivityLifecycleProvider`](https://github.com/trello/RxLifecycle/blob/master/rxlifecycle/src/main/java/com/trello/rxlifecycle/ActivityLifecycleProvider.java) or [`FragmentLifecycleProvider`](https://github.com/trello/RxLifecycle/blob/master/rxlifecycle/src/main/java/com/trello/rxlifecycle/FragmentLifecycleProvider.java). That's essentially all that `RxAppCompatActivity` is doing.
