### ISSUE TITLE
when use RxBus,  have some problem

### ISSUE THREAD

**Issue by woniu0936** [trello/RxLifecycle#125]
Hi, i used RxBus in my project, but i find a problem, here is没有code:
RxBus.getDefault().toObserverable(OperateEvent.class)
                              .compose(this.<OperateEvent>bindToLifecycle())
                              .observeOn(AndroidSchedulers.mainThread())
                              .subscribe(new Action1<OperateEvent>() {
                                      @Override
                                      public void call(OperateEvent operateEvent) {
                                           String operate = operateEvent.getOperate();
                                           Log.d(TAG, "--------rxSub-----operate----" + operate);
                                     }
                              });
Log did not print， but when i remove ".compose(this.<OperateEvent>bindToLifecycle())" , the log print success

**Comment by dlew** [comment]
You should strive to call `compose(bindToLifecycle())` as late as possible - after `observeOn` if possible.

Regardless, the issue tracker is for problems with the library itself. General usage questions should go to other forums, such as stackoverflow.com.
