### ISSUE TITLE
LifecycleTransformer lose type information?

### ISSUE THREAD

**Issue by arvabalazs** [trello/RxLifecycle#126]
```
Observable.just(1).compose(bindToLifecycle()).subscribe(/*int*/)
Single.just(1).compose(bindToLifecycle().forSingle()).subscribe(/*Object*/)
```
Is this behavior intended or a bug or a feature request?

Thank you,
Balazs

**Comment by dlew** [comment]
I feel like there's something missing from your sample. Either you're compiling with Java 8 (and the type information will propagate correctly) or you're compiling with Java 7 (and you need to explicitly cast the `bindToLifecycle()` call), like so:

```
Observable.just(1).compose(this.<Integer>bindToLifecycle()).subscribe(/*int*/)
Single.just(1).compose(this.<Integer>bindToLifecycle().forSingle()).subscribe(/*int*/)
```

In other words: If you were on Java 8, both would work. If you were on Java 7, neither would work.

**Comment by arvabalazs** [comment]
Hi,

thank you for your answer. Unfortunatelly this is not the case, because when I only switch in the very same project between those line, and the result is different.
The explicit cast helps me at the Single case, but it is ugly.

```
Observable.just(1).compose(bindToLifecycle()).subscribe(new Action1<Integer>()
		{
			@Override
			public void call(Integer integer)
			{

			}
		});

Single.just(1).compose(bindToLifecycle().forSingle()).subscribe(new Action1<Integer>()
		{
			@Override
			public void call(Integer o)
			{

			}
		});
```

The second one cause a compiler error in a same file. I am using the latest AndroidStudio with pretty updated libs.

Can you double check?

Thank you,
Balazs

**Comment by dlew** [comment]
Hmm, I checked it out on Java 8 and you're right, it's not working there.

It may be a limitation of Java's type inference. I'll have to look deeper.

**Comment by arvabalazs** [comment]
Thank you, I am waiting for your feedback!

Balazs

**Comment by dlew** [comment]
Just a warning, this is fairly low on my priority queue right now because A. I don't use `Single` that often myself and B. there's a clear workaround (using `this.<Integer>`).
