### ISSUE TITLE
Split out Android-specific portions from base RxJava-only libs

### ISSUE THREAD

**Issue by dlew** [trello/RxLifecycle#127]
Right now `RxLifecycle` could be composed of two parts:

1. The basic lifecycle/event system, with any input.

2. The Android-specific system, with Activities/Fragments as input.

It'd be better if we split these into two modules, so people could use the lifecycle behavior separately from Android.

**Comment by felipecsl** [comment]
👍 that's exactly what we did in RxGroups, 2 separate artifacts, 1 java only, 1 android lib

**Comment by krn1** [comment]
I like this idea too

**Comment by dlew** [comment]
Done in #143
