### ISSUE TITLE
RxFragment support requestPermissions()

### ISSUE THREAD

**Issue by enginebai** [trello/RxLifecycle#134]
Hi, it would be nice to support `Fragment.requestPermissions()` for `targetSdkVersion` >= 23.

**Comment by dlew** [comment]
I don't understand what you want. Could you elaborate what sort of API you're interested in having?

**Comment by enginebai** [comment]
My original fragment extend `android.support.v4.app.Fragment` and I use `Fragment.requestPermissions(@NonNull String[] permissions, int requestCode)`, but `RxFragment` does not support this method if I change to inherit it.
