### ISSUE TITLE
Common super-interface for FragmentLifecycleProvider and ActivityLifecycleProvider

### ISSUE THREAD

**Issue by tbsandee** [trello/RxLifecycle#137]
Wondering if there would be room for a super-interface (`BaseLifecycleProvider`?) that contains the method common to both of the concrete types `FragmentLifecycleProvider` and `ActivityLifecycleProvider`. That would allow generic handling of calls to `bindToLifecycle()` without a wrapper.

If so, I'm happy to provide a PR if you can provide guidance on naming conventions that you'd like.

**Comment by tbsandee** [comment]
FWIW, this is what I'm using now:

```java
abstract public class LifecycleProvider {
  @Nonnull
  static public LifecycleProvider from(ActivityLifecycleProvider provider) {
    return new LifecycleProvider() {
      @Override
      @Nonnull
      public <T> LifecycleTransformer<T> bindToLifecycle() {
        return provider.bindToLifecycle();
      }
    };
  }

  @Nonnull
  static public LifecycleProvider from(FragmentLifecycleProvider provider) {
    return new LifecycleProvider() {
      @Override
      @Nonnull
      public <T> LifecycleTransformer<T> bindToLifecycle() {
        return provider.bindToLifecycle();
      }
    };
  }

  @Nonnull
  abstract public <T> LifecycleTransformer<T> bindToLifecycle();
}
```

**Comment by dlew** [comment]
That sounds reasonable to me. We can work it into the next release.

**Comment by tbsandee** [comment]
Cool, well, I've created PR #138 with a quick stab if it helps.

**Comment by dlew** [comment]
#138 is a good start. I'm keeping this open because I want to investigate if we should just get rid of `FragmentLifecycleProvider` and `ActivityLifecycleProvider` altogether. The only APIs using them are more internal than anything else (except Navi, but that's so experimental I don't mind making people change their code to adapt).

**Comment by tbsandee** [comment]
Yeah, totally get it. I did do the minimal change without breaking existing public APIs. Thanks!
