### ISSUE TITLE
the version of the support jar

### ISSUE THREAD

**Issue by 836154942** [trello/RxLifecycle#141]
hello ,thanks for you rxlifecyle,in my project ,happend arrts  already define . can you tell the version  of the  android support jar .thanks

**Comment by dlew** [comment]
I have only the vaguest idea of what you're asking for, so here goes...

Our dependencies are defined here: https://github.com/trello/RxLifecycle/blob/master/build.gradle

**Comment by 836154942** [comment]
sorry my english is not all . compile with your   'com.trello:rxlifecycle-components:0.6.1'  ,the support-v4 is 
Version conflicted.

**Comment by dlew** [comment]
Your build should use whatever is the highest version for support library. It doesn't matter so much what is defined in this library as a result.

**Comment by 836154942** [comment]
thanks .  compile witch 'com.android.support:support-v4:23.4.0' can Correctly compile
