### ISSUE TITLE
Question about completion

### ISSUE THREAD

**Issue by tir38** [trello/RxLifecycle#145]
Given this:

```
myObservable
    .compose(RxLifecycle.bindUntilEvent(lifecycle, ActivityEvent.DESTROY))
    .subscribe();
```

I understand that RxLifecycle will terminate the stream (by calling onComplete) when destroy lifecycle event is detected. This prevents us from keeping stream open longer than desired.

But what happens if myObservable emits complete before destroy lifecycle? Will RxLifecycle also emit complete or will it keep the pipe open until destroy lifecycle event?

**Comment by dlew** [comment]
If `myObservable` emits `onCompleted` then the stream ends as well.

Internally, RxLifecycle uses the `takeUntil()` operator, so you can think of its behavior in the same way.

**Comment by tir38** [comment]
Ahh ok, it's the `BehaviorSubscription` never completes?

**Comment by dlew** [comment]
I don't understand your question. What is a `BehaviorSubscription`?

**Comment by tir38** [comment]
Sorry. I meant

`private final BehaviorSubject<ActivityEvent> lifecycleSubject = BehaviorSubject.create();` inside `RxAppCompatActivity`. This Subject never receives onComplete though.

**Comment by dlew** [comment]
Yes, that's because it runs the lifecycle. It's what's feeding the events to `takeUntil`.

Basically - what you want to do is fine and the expected behavior of RxLifecycle. If you have deeper questions about how RxLifecycle works, I invite you to explore the source code.
