### ISSUE TITLE
Does it behave normally ?

### ISSUE THREAD

**Issue by UsherBaby** [trello/RxLifecycle#150]
When compose called before subscribe(....) , things go well.But compose called before map(...) , ActivityEvent.DESTROY make no sense .

-------------------code------------------------
Observable.just(0)
                .subscribeOn(Schedulers.newThread())
            **//  .compose(bindUntilEvent(ActivityEvent.DESTROY))** 
                .map(...)
                .observeOn(AndroidSchedulers.mainThread())
                .compose(bindUntilEvent(ActivityEvent.DESTROY))
                .subscribe(....)

**Comment by dlew** [comment]
What goes wrong when it's called before `map()`?

**Comment by UsherBaby** [comment]
@dlew  It does not unsubscribe the sequence , when the activity's onDestory() is called .

-------------------Things go well code------------------------
Observable.just(0)
.subscribeOn(Schedulers.newThread())
.compose(bindUntilEvent(ActivityEvent.DESTROY)) 
.map(...)
.observeOn(AndroidSchedulers.mainThread())
_compose(bindUntilEvent(ActivityEvent.DESTROY))_
.subscribe(....)


-------------------Things go wrong code------------------------
Observable.just(0)
.subscribeOn(Schedulers.newThread())
_.compose(bindUntilEvent(ActivityEvent.DESTROY))_ 
.map(...)
.observeOn(AndroidSchedulers.mainThread())
.subscribe(....)

**Comment by dlew** [comment]
Sorry for dropping the ball on this one, forgot to follow up.

I've been trying to reproduce this on my end but I cannot.

I'm going to close this for now unless you have a more full sample demonstrating the issue, but as far as I can tell it's working correctly right now.
