### ISSUE TITLE
CompletableTransformer is removed in rxjava 1.2.0

### ISSUE THREAD

**Issue by hamberluo** [trello/RxLifecycle#151]

**Comment by vanniktech** [comment]
`CompletableTransformer` : renamed to `Completable.Transformer`

**Comment by dlew** [comment]
Oh neat, so there's no way for the library to be backwards compatible. :P

**Comment by vanniktech** [comment]
They were able to make that change since Completable was marked as Experimental

**Comment by dlew** [comment]
I know, I think I've learned a lesson here not to support experimental APIs in a more stable lib.

The problem is that people wanted support for completable/etc...

**Comment by dlew** [comment]
I'm not 100% sure, but I think that even if you're not using `Completable.Transformer` it's used in the source code of `RxLifecycle`. So unless you're proguarding all that stuff out, the compiler will complain that `RxLifecycle` is referencing classes that don't exist.

**Comment by markrietveld** [comment]
Confirming: I don't use `CompletableTransformer`, and RxLifecycle 0.8.0 compiles and works for me with RxJava 1.1.9.
