### ISSUE TITLE
Conflict with dependency 'com.google.code.findbugs:jsr305'.

### ISSUE THREAD

**Issue by shgharib** [trello/RxLifecycle#154]
Conflict with dependency 'com.google.code.findbugs:jsr305'. Resolved versions for app (3.0.1) and test app (2.0.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

The gradle file:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"
    defaultConfig {
        applicationId "com.test.testnewandroidstudio"
        minSdkVersion 9
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:24.2.1'
    testCompile 'junit:junit:4.12'

    compile 'com.trello:rxlifecycle:0.8.0'

}

```

**Comment by dlew** [comment]
You'll have to include the right JSR in `testCompile` to get it working.

**Comment by shgharib** [comment]
Thank you, I added 

>     androidTestCompile 'com.google.code.findbugs:jsr305:3.0.1'

now it's working.

**Comment by Y-JH** [comment]
added it , it worked.thanks

**Comment by asifAli101** [comment]
mine is not working, help please

**Comment by OlegSuhih** [comment]
> 
> 
> mine is not working, help please

[A solution](https://stackoverflow.com/questions/55502447/cannot-find-a-version-of-com-google-code-findbugsjsr305/55502972)

androidTestImplementation 'com.android.support.test.espresso:espresso-contrib:3.0.2', {
    exclude group: 'com.google.code.findbugs', module: 'jsr305'
}
