### ISSUE TITLE
CustomViews lifecycle?

### ISSUE THREAD

**Issue by BugsBunnyBR** [trello/RxLifecycle#155]
Hi, I would like to know if it is possible to have an pre-written LinearLayout/RelativeLayout/FrameLayout with support to RxLifecycle.
Thanks folks.

**Comment by UsherBaby** [comment]
public static <T> LifecycleTransformer<T> bindView(@NonNull final View view)
in RxLifecycleAndroid . Is that what you need ?

**Comment by UsherBaby** [comment]
@BugsBunnyBR 
public static LifecycleTransformer bindView(@NonNull final View view)
in RxLifecycleAndroid . Is that what you need ?

**Comment by W-quan** [comment]
I want to unsubscribe when View is gone, but `RxlifecycleAndroid.bindView()` is unsubscribe when View onDetachedFromWindow().

**Comment by dlew** [comment]
@W-quan How do you define a View being gone besides `onDetachedFromWindow()`? How much more gone can it be?
