### ISSUE TITLE
 Gradle build finished with 1 error(s) and 1 warning(s) 

### ISSUE THREAD

**Issue by ljf1172361058** [trello/RxLifecycle#178]
Module Gradel:
    
    // 编译【compile】RxJava
    compile 'io.reactivex:rxjava:1.2.2'
    // 编译【compile】RxAndroid
    compile 'io.reactivex:rxandroid:1.2.1'
    // 编译【compile】RxLifecycle(解决RxJava内存泄露问题,包含以下三个【Solve the problem of RxJava memory leaks, includes the following three】)
    compile 'com.trello:rxlifecycle:1.0'
    // If you want to bind to Android-specific RxLifecycle
    compile 'com.trello:rxlifecycle-android:1.0'
    // If you want pre-written Activities and Fragments you can subclass as providers
    compile 'com.trello:rxlifecycle-components:1.0'

我依赖了3个,但是Gradle出错了【I rely on the three, but Gradle went wrong】:
Warning:Conflict with dependency 'com.google.code.findbugs:jsr305'. Resolved versions for app (3.0.1)       and test app (2.0.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Error:Execution failed for task ':app:prepareDebugAndroidTestDependencies'.
> Dependency Error. See console for details.

能帮帮我么？【Can help me?】

**Comment by dlew** [comment]
You'll need to compile all your sources with a specific version of `com.google.code.findbugs:jsr305` so that they don't conflict in the test app.

**Comment by ljf1172361058** [comment]
@dlew  thanks.
In the project build. Gradle Android with {}:
```
configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:3.0.0'
}
```
Problem solved.
