### ISSUE TITLE
Min SDK 15?

### ISSUE THREAD

**Issue by dustin-graham** [trello/RxLifecycle#18]
I'd like to know why the minSDK for these libraries is 15. Seems restrictive. If I force override on my project (min 14), should I expect some things to break?

**Comment by jdreesen** [comment]
See https://github.com/trello/RxLifecycle/issues/13

**Comment by major-laslo** [comment]
Might be wise to put an explanation in the readme (though I guess many will still go for asking instead of reading), as people coming from old rxAndroid will be surprised by the jump in minSDK, even if you move the project down to minSDK 14.

**Comment by dlew** [comment]
@major-laslo Please read the linked #13.
