### ISSUE TITLE
Unsub and Resub Observable in Activity

### ISSUE THREAD

**Issue by Zulqurnain** [trello/RxLifecycle#180]
I have already posted a question in SO about the same issue , my location Observable get unsubscribe when app goes in background or home button pressed , but what if i want it to resubscribe automatically after activity become active !!!

Note: I know we can again subscribe it in onResume , problem here are parameters of Observables , i can't recreate them in onResume and why can't it be done by .compose(bindToLifecycle()) ?

**Comment by dlew** [comment]
RxLifecycle only handles unsubscription at this point. I've mused on the idea of automatically starting a subscription based on a lifecycle event but that would definitely increase the complexity of this.
