### ISSUE TITLE
Rx2: Crashes when used to transform a RxNavi-event

### ISSUE THREAD

**Issue by TillSimon** [trello/RxLifecycle#182]
I use `rxlifecycle2` together with `navi2` and I try to subscribe to a navi-event and compose it with `RxLifecycle` in an Activity:

```
private final LifecycleProvider<ActivityEvent> provider
            = NaviLifecycle.createActivityLifecycleProvider(this);

public ActivityMain() {
        RxNavi.observe(this, Event.START)
                .compose(RxLifecycle.bind(provider.lifecycle()))
                .subscribe();
}
```
While the above works, it's not what I want and I get this exception...
```
java.lang.NullPointerException: The mapper function returned a null value.
at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:67)
at com.trello.navi2.rx.NaviOnSubscribe$EmitterListener.call(NaviOnSubscribe.java:51)
at com.trello.navi2.internal.NaviEmitter.emitEvent(NaviEmitter.java:139)
at com.trello.navi2.internal.NaviEmitter.onPostCreate(NaviEmitter.java:228)
at com.trello.navi2.component.support.NaviAppCompatActivity.onPostCreate(NaviAppCompatActivity.java:63)
```
...when using either of the following:

`.compose(RxLifecycle.bindUntilEvent(provider.lifecycle(), ActivityEvent.DESTROY))`
`.compose(RxLifecycleAndroid.bindActivity(provider.lifecycle()))`
`.compose(provider.bindToLifecycle())`

**Comment by dlew** [comment]
Ah, that's a problem. I can fix that up quickly.

**Comment by dlew** [comment]
Fixed.

I'm going to wait a day or two before releasing 2.0.1, to see if anything else comes up.

**Comment by TillSimon** [comment]
Great. Thanks heaps!

**Comment by TillSimon** [comment]
@dlew Btw, do
`.compose(RxLifecycleAndroid.bindActivity(provider.lifecycle()))`
and
`.compose(lifecycleProvider.bindToLifecycle())`
do the same thing? (So, e.g. when subscribed in onResume terminate it in onPause)

And, does
`.compose(RxLifecycle.bind(lifecycleProvider.lifecycle()))`
really terminate on whatever lifecycle event comes next? Like when subscribed in onCreate it would terminate in onCreateView for a Fragment? What would that be useful for?

**Comment by dlew** [comment]
Yes, the first two are the same thing.

And yes, the second one terminates the moment any event occurs. It's used internally for everything and has had one or two helpful applications outside of the library itself.

**Comment by TillSimon** [comment]
Thanks for the update. Now what happens is, for this...

```
public ActivityMain() {
        RxNavi.observe(this, Event.CREATE)
                .map(o -> 1)
                .compose(provider.bindToLifecycle())
                .subscribe(i -> Timber.d("item %d", i),
                        t -> Timber.e("excp %s", ((CompositeException) t).getExceptions().toString())
                );
    }
```
...it emits the item and then terminates with the exception from before.
```
item 1
excp [java.lang.NullPointerException: The mapper function returned a null value.]
```

**Comment by dlew** [comment]
Are you sure you're not still using 2.0? I just ran your test and it works fine for me.

**Comment by TillSimon** [comment]
Now it works.
The gradle was synced to 2.0.1, but apparently took a couple of rebuilds until it got picked up correctly.
Sorry for that.
