### ISSUE TITLE
Will you support more components ?

### ISSUE THREAD

**Issue by yakovchang** [trello/RxLifecycle#186]
Will you support more components ? such as Dialog, PopupWindow.

**Comment by dlew** [comment]
`Dialog` can be wrapped with `DialogFragment` which is already supported.

I'm not sure how we would support `PopupWindow`. What events would it track?

**Comment by ayjindal** [comment]
@dlew Any plans to support `ListFragment`?

**Comment by dlew** [comment]
Unlikely. I view `ListFragment` as wholly unnecessary. I think it's generally better to just include your own `ListView` in the layout and bind to it.

**Comment by ianomad** [comment]
@dlew 

What about services?

**Comment by dlew** [comment]
Services are a little more weird because their lifecycle isn't so cut and dry. If someone can propose how it'd work then we could do it, but they aren't the same "power up, then power down" lifecycle that Activity has.

**Comment by ianomad** [comment]
What about custom views or adapter items?

**Comment by dlew** [comment]
There's already View support: https://github.com/trello/RxLifecycle/blob/1.x/rxlifecycle-android/src/main/java/com/trello/rxlifecycle/android/RxLifecycleAndroid.java#L98

As for adapter items, what sort of lifecycle do they have?

**Comment by UsherBaby** [comment]
BottomSheetDialogFragment

**Comment by semireg** [comment]
Conductor Controllers would be a nice addition.

**Comment by Zeyad-37** [comment]
What about AppCompatAcitivity & Fragment v4?

**Comment by dlew** [comment]
I think at this point I'm not going to be supporting any more components explicitly.
