### ISSUE TITLE
compose (io.reactivex.ObservableTransformer<Object>) in observable cannot be applied to  (com.trello.rxlifecycle2.LifecycleTransformer<Object>) 

### ISSUE THREAD

**Issue by jdsjlzx** [trello/RxLifecycle#190]
The code is as follows:

`
Observable.just(1)
                        .compose(RxLifecycle.bindUntilEvent(context.lifecycle(), ActivityEvent.DESTROY));
`

Tips are as follows:

`
compose (io.reactivex.ObservableTransformer<Object>) in observable cannot be applied to  (com.trello.rxlifecycle2.LifecycleTransformer<Object>) 
`

If I use the Flowable,Tips are as follows:

`
compose (io.reactivex.FlowableTransformer<Object>) in observable cannot be applied to  (com.trello.rxlifecycle2.LifecycleTransformer<Object>) 
`

In fact, I want to a custom FlowableTransformer,the code is as follows:

`

public FlowableTransformer<T, T> io_main(final RxAppCompatActivity context) {
        return new FlowableTransformer<T, T>() {

            @Override
            public Publisher<T> apply(Flowable<T> flowable) {

                return  flowable
                        .subscribeOn(Schedulers.io())
                        .doOnSubscribe(new Consumer<Subscription>() {
                            @Override
                            public void accept(Subscription subscription) throws Exception {
                                DialogHelper.showProgressDlg(context, mMessage);
                            }
                        })
                        .subscribeOn(AndroidSchedulers.mainThread())
                        .observeOn(AndroidSchedulers.mainThread())
                        .compose(RxLifecycle.bindUntilEvent(context.lifecycle(), ActivityEvent.DESTROY));
            }
        };
    }
`

`compose(RxLifecycle.bindUntilEvent(context.lifecycle(), ActivityEvent.DESTROY))` prompt error

Looking forward to your help, thank you

**Comment by dlew** [comment]
If you're using Java 7 for compilation then you may need to include hints for the generics, like so:

```java
Observable.just(1).
  compose(RxLifecycle.<Integer, ActivityEvent>bindUntilEvent(lifecycle(), ActivityEvent.DESTROY))
```

**Comment by jdsjlzx** [comment]
I try according to your proposal,but there is a problem, prompt is as follows
![compose](http://img.blog.csdn.net/20161203091627160)

Looking forward to your help, thank you

**Comment by jdsjlzx** [comment]
It works，thank you
