### ISSUE TITLE
run in android blow 5.0

### ISSUE THREAD

**Issue by duwurensheng010** [trello/RxLifecycle#197]
FATAL EXCEPTION: main java.lang.VerifyError: com/trello/rxlifecycle/components/support/RxAppCompatActivity

**Comment by dlew** [comment]
`VerifyError` is most likely a build problem on your end. If you can create a sample that reproduces it then I'll look into it.

**Comment by mradzinski** [comment]
```VerifyError``` is indeed a build problem on @duwurensheng010 end and nothing to do with the library. It's a long shot, but judging by the _5.0_ in the title and assuming that _blow_ is actually meant to say _below_... 65K methods.
