### ISSUE TITLE
ActivityEvent.DESTROY and isFinishing

### ISSUE THREAD

**Issue by storix** [trello/RxLifecycle#200]
Hi,

There is such code snippet in the _Usage_ section:

```
myObservable
    .compose(RxLifecycle.bindUntilEvent(lifecycle, ActivityEvent.DESTROY))
    .subscribe();
```

Are there any way to check whether  `ActivityEvent.DESTROY` event was emitted when `isFinishing = true | false`?

Just in case, here is the quote from the Android [docs:](https://developer.android.com/reference/android/app/Activity.html#onDestroy())

> Perform any final cleanup before an activity is destroyed. This can happen either because the activity is finishing (someone called finish() on it, or because the system is temporarily destroying this instance of the activity to save space. You can distinguish between these two scenarios with the isFinishing() method.

So can we complete the observable sequence only when the activity is finishing (not just being temporarily destroyed)? Something like this:

```
@Override
  protected void onDestroy() {
    super.onDestroy();
    if (isFinishing()) {
      // Emit event here
    } 
  }
```

And then

```
myObservable
    .compose(RxLifecycle.bindUntilEvent(lifecycle, ActivityEvent.DESTROY_AND_FINISH))
    .subscribe();
```

**Comment by dlew** [comment]
I don't understand your use case. It seems like you want an `Observable` subscription to not be canceled in the case that the `Activity` was destroyed (but not finished)?

I would argue that you should unsubscribe from observables in `onDestroy()` regardless of whether it's finishing or not. If the `Activity` is being recreated then you actually get a new instance of `Activity` and it would be detrimental to hold onto subscriptions referencing the old `Activity`.

**Comment by storix** [comment]
> If the Activity is being recreated then you actually get a new instance of Activity and it would be detrimental to hold onto subscriptions referencing the old Activity.


I'm sorry If I misunderstood the purpose of this library, but in accordance with the `README`: 

> RxLifecycle does not actually unsubscribe the sequence. Instead it terminates the sequence.

For example, I can store an observable in a retained fragment (so that every time the `Activity` is recreated I can retrieve the same observable instance). I just thought it is possible to complete the sequence automatically when the `Activity` is being destroyed _and_ finished, without actually managing subscriptions.

Imagine a common use case: a presenter which survives a configuration change. This presenter can be saved in some static store or in a retained fragment (or even using a `Loader`). What if the presenter subscribes to an observable but this observable must be completed only when the `Activity` is finished (not temporarily destroyed due to a device rotation). Of course, I can use an interface to pass required events manually and unsubscribe when needed. Just thought I could achieve this more easily with this library by binding such observable to `ActivityEvent.DESTROY_AND_FINISH`.

**Comment by dlew** [comment]
Yes, this library terminates sequences. It does not technically unsubscribe. I use the term "unsubscribe" anyways because that's how most people understand what it's doing (and it's basically trying to mimic that behavior in a safe way).

-----

On to your actual question. If the `Subscription` lives beyond the lifecycle of a single `Activity` then this library does not apply to it. That said, it's possible to unsubscribe from an `Observable` without terminating the `Observable` itself. The way I use it, the `Observable` lives on between `Activities` but each individual `Activity` unsubscribes/resubscribes as necessary.

That may not line up with your presenter-based setup.

**Comment by storix** [comment]
Ok, thank you for the reply. It is more clear now. 

By the way, I've just found [FRAGMENT_EVENT_MAP](https://github.com/trello/RxLifecycle/blob/1a78ef1cc772e99e74aace5091b66ece7615764a/rxlifecycle-navi/src/main/java/com/trello/rxlifecycle/navi/NaviLifecycleMaps.java#L36). Correct me if I'm wrong, but it seems that in the case of the retained fragment the `FragmentEvent.DESTROY` would be exactly the same as the aforementioned  `ActivityEvent.DESTROY_AND_FINISH` :)

It is OK to use the retained fragment as a subclass of `RxFragment`?

**Comment by dlew** [comment]
Yeah, that's fine.

**Comment by storix** [comment]
Thanks, I'm closing the issue
