### ISSUE TITLE
Tests break with RxJava 2.0.2+

### ISSUE THREAD

**Issue by Jawnnypoo** [trello/RxLifecycle#201]
I am trying to investigate what exactly is going on, but currently, if you update the library to 2.0.2 and beyond and run the tests, `RxLifecycleTest.testBindLifecycle` and `RxLifecycleTest.testBindLifecycleOther` fail with the test observer being disposed. 

I am thinking it might be related to this PR?
https://github.com/ReactiveX/RxJava/pull/4873

**Comment by dlew** [comment]
Thanks for reporting. It is indeed related to that PR.

Fixing it only involved modifying tests, so I'm not going to release a new version of RxLifecycle; the internals of the library are still sound.

**Comment by Jawnnypoo** [comment]
Ah okay, glad to hear it! 👍
