### ISSUE TITLE
when i add the dependencies, gradle report an error 

### ISSUE THREAD

**Issue by weituotian** [trello/RxLifecycle#204]
`compile 'com.trello:rxlifecycle:1.0'`

![image](https://cloud.githubusercontent.com/assets/7270968/23911949/4d1fa02e-0919-11e7-8386-ba050e86d583.png)

**Comment by dlew** [comment]
Please see the linked information for what's going on: https://sites.google.com/a/android.com/tools/tech-docs/new-build-system/user-guide#TOC-Resolving-conflicts-between-main-and-test-APK

**Comment by weituotian** [comment]
actually i have no idea to add or modify some configurtion after i had read the acticle. @dlew 
![image](https://cloud.githubusercontent.com/assets/7270968/23915010/b96401ae-0922-11e7-9318-6ed18828e84b.png)
