### ISSUE TITLE
Standard java lib can't dependence on "relifecyle"  module

### ISSUE THREAD

**Issue by UsherBaby** [trello/RxLifecycle#206]
apply plugin: 'java' is used in  "relifecyle"  module  . but my standard java lib module in Android Studio can't dependence on it

**Comment by dlew** [comment]
I don't understand the problem. Could you elaborate or post some code?

**Comment by UsherBaby** [comment]
@dlew Sorry for my poor English !  There is a java module which applies plugin: 'java'  in AndroidStudio . When I add compile 'com.trello.rxlifecycle2:rxlifecycle:2.0.1' to it , gradle dependencies go wrong ! I don't know why , because rxlifecycle is also a java module too !

**Comment by dlew** [comment]
Chances are you're dependencies are misconfigured in some way. I still don't exactly understand what's going on, so I am going to need a reproduction of the issue.

**Comment by UsherBaby** [comment]
@dlew I forgot 'com.google.code.findbugs:jsr305:3.0.1' . Well , please close this issuse
