### ISSUE TITLE
OnTerminateDetach can be used with RxLifecycle?

### ISSUE THREAD

**Issue by jdsjlzx** [trello/RxLifecycle#207]
in RxJava：
`
/**
* Nulls out references to the upstream producer and downstream Subscriber if
     * the sequence is terminated or downstream unsubscribes.
*/
@Experimental
public final Observable<T> onTerminateDetach() {
    return create(new OnSubscribeDetach<T>(this));
}
`

OnTerminateDetach operators can solve the problem of memory leaks, then can be used together with RxLifecycle?

**Comment by dlew** [comment]
You can use `onTerminateDetach()` if you want. We're not going to add an experimental API to this library though.
