### ISSUE TITLE
How can I use bindToLifecycle() in MVP Presenter ?

### ISSUE THREAD

**Issue by littlezan** [trello/RxLifecycle#214]
How can I use bindToLifecycle() ... in MVP `Presenter` or some where not extends `RxActivity` ...

thinks

**Comment by dlew** [comment]
You can pass the lifecycle `Observable` to your `Presenter` and use it from there.

I'm closing this because GitHub issues are for bugs and feature requests for RxLifecycle. For usage questions, stackoverflow.com or the like is a better avenue.
