### ISSUE TITLE
Support for new android lifecycle events

### ISSUE THREAD

**Issue by dalewking** [trello/RxLifecycle#215]
As announced today: https://developer.android.com/topic/libraries/architecture/lifecycle.html

Seems to be an officially supported equivalent of Navi.

**Comment by dlew** [comment]
I'd be down with a navi-like extension built on top of the new arch. I'm not sure when I'll get time to do it though.

**Comment by dalewking** [comment]
It was announced 2 days ago and you don't already have a working implementation?  ;-)

Just created the issue as a reminder to do it someday.

**Comment by dlew** [comment]
Many thanks to @evant for adding support!
