### ISSUE TITLE
What is the simile of MediatorLiveData#addSource

### ISSUE THREAD

**Issue by juanpmarin** [trello/RxLifecycle#226]
Hi !
The MediatorLiveData of the Architecture Components has a method called addSource, the description is:

>  addSource(LiveData\<S> source, Observer\<S> onChanged) 
> Starts to listen the given source LiveData, onChanged observer will be called when source value was changed. 

So the MediatorLiveData listen to changes on the added source but respecting the lifecycle of the MediatorLiveData, how can I achieve this with RxJava ? 

I'm triying to port this [class](https://github.com/googlesamples/android-architecture-components/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/repository/NetworkBoundResource.java) to RxJava.

I hope I was clear, thanks !
Sorry for my english

**Comment by dlew** [comment]
The simile would be merging multiple `Observable<LifecycleEvent>` as the source for events.

The issue tracker is for bugs and feature requests in RxLifecycle, not a help request forum. As such, I'm closing this issue.
