### ISSUE TITLE
Could sure use a "Getting Started"

### ISSUE THREAD

**Issue by RobLewis** [trello/RxLifecycle#227]
The ReadMe uses too many unfamiliar terms that aren't defined. 
What is a "lifecycle stream? In this context, what's meant by "binding"? What exactly is meant by "automatically complete sequences based on a second lifecycle stream" (and where's the "_first_ lifecycle stream"?) What, ultimately is RxLifecycle _for_? What are its benefits over other approaches? 
How about a very short example showing the same program with & without RxLifecycle? 

I've been successfully using RxJava for some time now (and reading lots about it), but still apparently don't know enough to crack the RxLifecycle code. Anyone else feel my pain?

**Comment by dlew** [comment]
Perhaps a sample would help? https://github.com/trello/RxLifecycle/tree/2.x/rxlifecycle-sample

> How about a very short example showing the same program with & without RxLifecycle?

https://github.com/dlew/android-subscription-leaks

**Comment by RobLewis** [comment]
Thank you, those will no doubt help. But I would still like answers to the questions in my OP.

**Comment by dlew** [comment]
Honestly, I don't have the will or the time to answer these questions if you're not willing to look at the samples and answer them for yourself. If the README and two different sample apps can't help you, then too bad.

**Comment by dlew** [comment]
Another possible avenue: AutoDispose does a very similar thing to RxLifecycle, perhaps you will find their documentationmore appealing: https://github.com/uber/AutoDispose
