### ISSUE TITLE
can't find referenced class javax.annotation.Nonnull

### ISSUE THREAD

**Issue by DaiFalin** [trello/RxLifecycle#228]
minifyEnabled true

Information:Gradle tasks [:app:assembleDebug]
Information:0 errors
Information:0 warnings
Information:See complete output in console
Warning:com.trello.rxlifecycle2.LifecycleProvider: can't find referenced class javax.annotation.Nonnull
Warning:com.trello.rxlifecycle2.LifecycleProvider: can't find referenced class javax.annotation.CheckReturnValue
Warning:com.trello.rxlifecycle2.LifecycleProvider: can't find referenced class javax.annotation.Nonnull
Warning:com.trello.rxlifecycle2.LifecycleProvider: can't find referenced class javax.annotation.CheckReturnValue
Warning:com.trello.rxlifecycle2.LifecycleProvider: can't find referenced class javax.annotation.Nonnull
Warning:com.trello.rxlifecycle2.LifecycleProvider: can't find referenced class javax.annotation.CheckReturnValue
Warning:com.trello.rxlifecycle2.RxLifecycle: can't find referenced class javax.annotation.Nonnull
Warning:com.trello.rxlifecycle2.RxLifecycle: can't find referenced class javax.annotation.CheckReturnValue
Warning:com.trello.rxlifecycle2.RxLifecycle: can't find referenced class javax.annotation.Nonnull
Warning:com.trello.rxlifecycle2.RxLifecycle: can't find referenced class javax.annotation.CheckReturnValue
Warning:com.trello.rxlifecycle2.RxLifecycle: can't find referenced class javax.annotation.Nonnull
Warning:com.trello.rxlifecycle2.RxLifecycle: can't find referenced class javax.annotation.CheckReturnValue
Warning:com.trello.rxlifecycle2.RxLifecycle: can't find referenced class javax.annotation.Nonnull
Warning:there were 18 unresolved references to classes or interfaces.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForDebug'.
> Job failed, see logs for details
Information:BUILD FAILED
Information:Total time: 7.618 secs

**Comment by dlew** [comment]
Could you provide a sample app showing the same problems?

**Comment by jp1017** [comment]
@DaiFalin 

Add this to your `proguard-rules.pro` file: :smile: 

```
-dontwarn class javax.annotation.**
```
