### ISSUE TITLE
Old Google Support Library brakes Robolectric tests

### ISSUE THREAD

**Issue by sereden** [trello/RxLifecycle#234]
```RxLifecycle 2.1.0``` uses Google Support Library ver ```25.3.1``` however if application uses version  ```26.0.1``` some robolectric tests that use ```SupportFragmentTestUtil``` crash with 

```
java.lang.NoSuchMethodError: android.support.v4.view.LayoutInflaterCompat.setFactory2(Landroid/view/LayoutInflater;Landroid/view/LayoutInflater$Factory2;)V
```
This happens due to fact that a lot of methods had been deleted and renamed.
I guess it worth to update this library

**Comment by dlew** [comment]
Closed via #235
