### ISSUE TITLE
Fragment 中使用RxLifecycle

### ISSUE THREAD

**Issue by 17722525963** [trello/RxLifecycle#243]
Fragment中使用

RxView.clicks(test)
                .throttleFirst(2000, TimeUnit.MILLISECONDS)
                .compose(this.bindUntilEvent(FragmentEvent.STOP))
                .subscribe(new Observer<Object>() {...}

 .compose(this.bindUntilEvent(FragmentEvent.STOP)) 使用后没有效果，是不是我的方式有问题？

**Comment by dlew** [comment]
Sorry, I don't speak that language - this will have to be translated before I can help.
