### ISSUE TITLE
Used Fragment

### ISSUE THREAD

**Issue by 17722525963** [trello/RxLifecycle#244]
In the following code
-------------------------------
RxView.clicks(test)
.throttleFirst(2000, TimeUnit.MILLISECONDS)
.compose(this.bindUntilEvent(FragmentEvent.STOP))
.subscribe(new Observer() {...}
--------------------------------
“.compose(this.bindUntilEvent(FragmentEvent.STOP))”   This line has no effect，
Please help me to see if there is a problem with my code，Thanks！

**Comment by dlew** [comment]
Could you give a larger example? Out of context it's hard to diagnose what's going wrong.

**Comment by 17722525963** [comment]
Sorry, some time ago something delayed.
The complete code is as follows:

RxView.clicks(test)
                .throttleFirst(2000, TimeUnit.MILLISECONDS)
                .compose(bindUntilEvent(FragmentEvent.PAUSE))
                .subscribe(new Observer<Object>() {
                    @Override
                    public void onSubscribe(@NonNull Disposable d) {

                    }

                    @Override
                    public void onNext(@NonNull Object o) {
                        Toast.makeText(getActivity(), "clicked！" + System.currentTimeMillis(), Toast.LENGTH_SHORT).show();
                    }

                    @Override
                    public void onError(@NonNull Throwable e) {

                    }

                    @Override
                    public void onComplete() {

                    }
                });

After running, close the screen, open again, or you can pop up the prompt, and has not been canceled.
Perhaps my understanding is wrong, if not, please forgive me!

**Comment by dlew** [comment]
I meant, where exactly is that code being called from? Like, is it being called in `onCreateView()`?

**Comment by 17722525963** [comment]
in onStart()

 @Override
    public void onStart() {
        super.onStart();

        RxView.clicks(test)
                .throttleFirst(2000, TimeUnit.MILLISECONDS)
                .compose(bindUntilEvent(FragmentEvent.PAUSE))
                .subscribe(new Observer<Object>() {
                    @Override
                    public void onSubscribe(@NonNull Disposable d) {

                    }

                    @Override
                    public void onNext(@NonNull Object o) {
                        Toast.makeText(getActivity(), "clicked！" + System.currentTimeMillis(), Toast.LENGTH_SHORT).show();
                    }

                    @Override
                    public void onError(@NonNull Throwable e) {

                    }

                    @Override
                    public void onComplete() {

                    }
                });
    }

**Comment by 17722525963** [comment]
Sorry, I put the operation on OnActivityCreated () can be normal implementation. But i wondered why this is why? Or in the use of Fragment RxLifecycle must be placed in the specified life cycle? In the Activity is the same? Can you answer it? thank you very much! - thanks from the small code farm very sincere!
