### ISSUE TITLE
Possible to use together with RxLoader?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [trello/RxLifecycle#246]
On RxLoader repo, the sample shows we have to un-register from it when the Activity/Fragment is destroyed :

https://github.com/L4Digital/RxLoader/blob/master/example/src/main/java/com/l4digital/rxloader/example/ExampleActivity.java

Is it possible to use both repos together, so that the lifecycle will unsubscribe automatically upon onDestroy ? 

I tried this:

        RxLoader<String> loader = new RxLoader<>(this, getObservable());
        RxLoaderCallbacks<String> callbacks = new RxLoaderCallbacks<>(loader);
        callbacks.observable
                .bindToLifecycle(this)
                .subscribe(...)

but it fails to build because bindToLifecycle isn't available there.

**Comment by dlew** [comment]
This issue tracker is for reporting issues with the RxLifecycle library. If you need help with usage, please refer to the [README](https://github.com/trello/RxLifecycle/blob/2.x/README.md) or [StackOverflow](https://stackoverflow.com/).

**Comment by AndroidDeveloperLB** [comment]
It just feels natural to use them both together.
