### ISSUE TITLE
Repo not recommended by author?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [trello/RxLifecycle#247]
Is this for real:
http://blog.danlew.net/2017/08/02/why-not-rxlifecycle/
?
If so, why not mention it in the repo itself?

**Comment by dlew** [comment]
Yes, it is for real.

It's not mentioned because people still do use it and like it. For those people, I'll keep supporting it.

**Comment by AndroidDeveloperLB** [comment]
I mean why not mention that you don't recommend it on the repo itself. Maybe even deprecate it, or present the disadvantages. 
People should know before using it. Not just the advantages, but also the disadvantages. 
Otherwise they take an informed decision.
