### ISSUE TITLE
Question: Removed AppObservable.bindActivity and AppObservable.bindFragment of RxAndroid 1.0.0

### ISSUE THREAD

**Issue by vanniktech** [trello/RxLifecycle#25]
Right now I'm in the process of upgrading to RxAndroid 1.0.1.

How can I get the same behavior as `AppObservable.bindActivity` and `AppObservable.bindFragment` as of [RxAndroid 0.24.0](https://github.com/ReactiveX/RxAndroid/blob/v0.24.0/rxandroid/src/main/java/rx/android/app/AppObservable.java)?

Since AppObservable used the isFinishing method for binding and that one is not available as an ActivityEvent I'm a little bit puzzled as how to I can sustain that behavior.

Is there any equivalent behavior / method?

**Comment by dlew** [comment]
There is no equivalent. `bindActivity` and `bindFragment` are not part of this library because they were ill-conceived and didn't really do what you'd expect. For example you could use it and your Observable might never end if it didn't emit at least one item after finishing.

**Comment by Rainer-Lang** [comment]
@dlew What alternatives do we have - for the same behaviour?

**Comment by dlew** [comment]
You can use RxLifecycle to get automatic closing and should use `observeOn(AndroidSchedulers.mainThread())` for the scheduling.
