### ISSUE TITLE
can you  add a proguard-rules.pro?

### ISSUE THREAD

**Issue by PantomZ** [trello/RxLifecycle#253]

**Comment by dlew** [comment]
As far as I know, there are no proguard rules needed for RxLifecycle. It doesn't rely on reflection or annotations, so all RxLifecycle code you use will automatically be kept by proguard.

**Comment by AllenVork** [comment]
@dlew thx for your answer.  I just took a look of the source code of clear and unsubscribe. The only difference between them is that unsubscribe method makes this.unsubscribed = true so you can't add subscription to it later. But I don't get it that why the clear method can clear references. Could you figure it out for me ?
