### ISSUE TITLE
method compose in class rx.Observable<T#1> cannot be applied to given types

### ISSUE THREAD

**Issue by osama-raddad** [trello/RxLifecycle#257]
i am trying to do this :

        Observable.just(object)
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .compose(RxLifecycleAndroid.bindActivity(this.lifecycle()))
                .subscribe();

and getting this :

> Error:(78, 17) error: method compose in class rx.Observable<T#1> cannot be applied to given types;
> required: Transformer<? super OnColorCreated,? extends R>
> found: LifecycleTransformer<Object>
> reason: no instance(s) of type variable(s) T#2 exist so that LifecycleTransformer<T#2> conforms to Transformer<? super OnColorCreated,? extends R>
> where R,T#1,T#2 are type-variables:
> R extends Object declared in method <R>compose(Transformer<? super T#1,? extends R>)
> T#1 extends Object declared in class rx.Observable
> T#2 extends Object declared in method <T#2>bindActivity(io.reactivex.Observable<ActivityEvent>)

**Comment by dlew** [comment]
If you're compiling with older versions of java, you may have to apply the generics explicitly to `bindActivity()` to make it compile. It looks like it cannot infer the generic type automatically.

**Comment by osama-raddad** [comment]
I am using java 8

>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }

**Comment by dlew** [comment]
Have you tried applying the generics manually? E.g. `RxLifecycleAndroid.<T>bindActivity(etc)`?
