### ISSUE TITLE
NoSuchFieldException: producerIndex

### ISSUE THREAD

**Issue by the4thfloor** [trello/RxLifecycle#26]
Since I updated from v0.1.0 to v0.2.0 I get this error. I think it is a proguard problem.

I found this `producerIndex` field in `rx.internal.util.unsafe.SpscArrayQueueProducerFields` and in `rx.internal.util.unsafe.SpmcArrayQueueProducerField`

This line `-keep class rx.internal.util.unsafe.** { *; }` in my proguard conf fixes the problem.

Maybe you want to add this info to the readme? :-)
I doesn't have this problem with RxAndroid or with RxBinding

**Comment by dlew** [comment]
This is a problem with the core RxJava project itself. Please refer to https://github.com/ReactiveX/RxJava/issues/3097.
