### ISSUE TITLE
Execution failed for task ':app:processDebugResources'

### ISSUE THREAD

**Issue by saravinfotech** [trello/RxLifecycle#263]
[rxlifecycleissues.txt](https://github.com/trello/RxLifecycle/files/1785535/rxlifecycleissues.txt)

Hi,

When I try to use 'com.trello.rxlifecycle2:rxlifecycle-components:2.2.1' component in my application I am getting gradle error where in it says error: failed linking references. Detailed error log attached.

I am using Android studio 3.2 Canary 4 and following  classpath 'com.android.tools.build:gradle:3.2.0-alpha04' in my gradle file. But the same works when I use 
compile 'com.trello.rxlifecycle2:rxlifecycle:2.0.1'
compile 'com.trello.rxlifecycle2:rxlifecycle-android:2.0.1'

Is there any issue with the canary build of Android studio? 
Can you tell me on if this is the mandatory compile 'com.trello.rxlifecycle2:rxlifecycle:2.2.1' on top of which we use the other libraries (pre-written Activities etc..)?

**Comment by dlew** [comment]
You're using unstable canary builds. I suspect you should be filing this with Google, not with me.

**Comment by saravinfotech** [comment]
Hey sorry did try it out and it is working fine with the stable version, my bad.
