### ISSUE TITLE
Restoration of Fragment cannot start the stream again

### ISSUE THREAD

**Issue by siralam** [trello/RxLifecycle#265]
I have a `Fragment A` that calls an API in `onCreateView`.  
The result will be used to display a list of objects.

`Fragment A` also has a button which navigates to `Fragment B`, by commiting a `FragmentTransaction` and replace itself. (`Fragment A` `onDestroyView` triggered)

Everything works well, but when I back from `Fragment B` to `Fragment A`(`Fragment A` `onCreateView` triggered), API is not called.

### Expected Behavior

The `Observables` that is created in `onCreateView` can trigger callbacks.

### Observed Behavior

The creation of `Observables` cannot trigger callbacks, if the Fragment is restored.

### Related Codes

Fragment A:

```java
public class BeansFragment extends BaseFragment {

   protected final LifecycleProvider<Lifecycle.Event> rxLifeCycleProvider = AndroidLifecycle.createLifecycleProvider(this);

   ...

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        ...
        retrofit.getSomeBeans()
                .subscribeOn(Schedulers.io())
                .unsubscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .compose(rxLifeCycleProvider.<List<Beans>>bindToLifecycle())
                .subscribe(new Observer<List<Beans>>() {
                    @Override
                    public void onSubscribe(Disposable d) {
                        
                    }

                    @Override
                    public void onNext(List<Beans> beans) {
                        if (getContext() == null) return;
                        setupBeans(beans);
                    }

                    @Override
                    public void onError(Throwable e) {

                    }

                    @Override
                    public void onComplete() {

                    }
                });
        ...
    }

    ...
}
```

I am pretty sure the library should be able to do this. So probably there is something wrong with my setup?

**Comment by dlew** [comment]
I'm on parental leave at the moment, sorry for slow reply.

See #131 for why things might be going wrong here. If that's not the case, let me know and I can dig more.

**Comment by siralam** [comment]
@dlew Congratulations haha! And I think #131 should be the reason. Thanks!
