### ISSUE TITLE
 Android dependency 'android.arch.lifecycle:runtime' has different version for the compile  and runtime

### ISSUE THREAD

**Issue by origin92** [trello/RxLifecycle#271]
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'android.arch.lifecycle:runtime' has different version for the compile (1.0.0) and runtime (1.0.3) classpath. You should manually set the same version via DependencyResolution

buildfailed ，how should i do？

**Comment by dlew** [comment]
You have to manually include that dependency to make sure you're getting the right version. See more here: https://stackoverflow.com/a/47066325
