### ISSUE TITLE
Explicit type arguments can be inferred

### ISSUE THREAD

**Issue by gongzelong0718** [trello/RxLifecycle#280]
```
public class BaseFragment extends Fragment implements FragmentLifecycleProvider
    @Override
    public <T> Observable.Transformer<? super T, ? extends T> bindUntilEvent(FragmentEvent event) {
        return RxLifecycle.bindUntilFragmentEvent(mLifecycleSubject, event);
    }
```
The interface is :
```
    Observable<ResponseEntity<GoodsMajorCategory, ResponseError>> getGoodsMajorCategoryAllSubcategories(
```

```
            mGoodsListSubscription =
                    goodsMajorCategoryObservable.observeOn(AndroidSchedulers.mainThread())
                            .compose(
                                    this.<ResponseEntity<GoodsMajorCategory, ResponseError>>bindUntilEvent(
                                            FragmentEvent.DESTROY))
                            .subscribe(new SubscriberAdapter<GoodsMajorCategory, ResponseError>() {
                                @Override
                                public void onResponse(@Nullable GoodsMajorCategory data) {
                                    onGetGoodsMajorCategoryAllSubcategoriesSuccess(data, true);
                                }

                                @Override
                                public void onFailed(@NonNull ApiError error) {
                                    onGetGoodsMajorCategoryAllSubcategoriesError();
                                }
                            });
```

Here I use 

```
.compose(
                                    this.<ResponseEntity<GoodsMajorCategory, ResponseError>>bindUntilEvent(
                                            FragmentEvent.DESTROY))
```

Android Studio warning
Explicit type arguments can be inferred less... (⌘F1) 
This inspection reports all calls to parametrized methods where explicit argument types can be omitted, since they will be unambiguously inferred by compiler. Such usages make code excessive and thus less readable. For example if you have a call to parametrized method like:
    this.<String>addItem("");
- the usage of <String> will be highlighted. 

But when I remove <ResponseEntity<GoodsMajorCategory, ResponseError>>, it will bring more errors.

`.subscribe(new SubscriberAdapter<GoodsMajorCategory, ResponseError>() {`
Could not resolve subscribe (anonymous GoodsMajorCategory and ResponseError)

<img width="634" alt="screen shot 2018-08-21 at 7 14 01 pm" src="https://user-images.githubusercontent.com/6286811/44398485-8a4fa700-a576-11e8-8524-913cd376eccc.png">

Could anyone know why and what I should do?

**Comment by dlew** [comment]
This is an issue tracker for bugs/features in the library, not a place to seek help using the library. I suggest going to stackoverflow.com for help.

You're welcome to update this if it turns out to be an issue with the library.
