### ISSUE TITLE
Does it use --> implementation 'com.trello.rxlifecycle3:rxlifecycle:3.0.0' , not rxlifecycle2?

### ISSUE THREAD

**Issue by HaowenLee** [trello/RxLifecycle#289]
When I use rxlifecycle2 with version 3.0.0, is not work.
README is 
`implementation 'com.trello.rxlifecycle2:rxlifecycle:3.0.0'`

**Comment by dlew** [comment]
Updated package name but forgot to update README. `com.trello.rxlifecycle3` should work.
