### ISSUE TITLE
Android Manifest merger error

### ISSUE THREAD

**Issue by vyshas** [trello/RxLifecycle#291]
```
Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-31:19 to override.
```

Trello version : 3.0.0

I haven't changed the support library and other dependencies in our app to AndroidX. If we have to use version 3.0.0 , should we upgrade our app dependencies to Android X ?

**Comment by dlew** [comment]
Yes.

However, you are under no obligation to upgrade to RxLifecycle 3.0.0 yet. The only substantive change is supporting AndroidX. You can continue to safely use RxLifecycle 2.2.2 until you are ready to upgrade.
