### ISSUE TITLE
android 26+ can't use rxlifecycle-android-lifecycle:3.0.0

### ISSUE THREAD

**Issue by Young-Joe** [trello/RxLifecycle#292]
My targetSdkVersion is 27. And I want to use android.arch.lifecycle,so MyActivity extends AppCompatActivity. But when i use AndroidLifecycle.createLifecycleProvider(this), it's wrong.
because androidx.lifecycle.LifecycleOwner not android.arch.lifecycle.LifecycleOwner .
So, how to solve is?

**Comment by dlew** [comment]
RxLifecycle 3.0.0 was pushed out to support AndroidX. If your codebase is not on AndroidX yet then you should not update.

Read up on the AndroidX migration [here](https://developer.android.com/jetpack/androidx/migrate) for more information.

**Comment by 13483865820** [comment]
> RxLifecycle 3.0.0 was pushed out to support AndroidX. If your codebase is not on AndroidX yet then you should not update.
> 
> Read up on the AndroidX migration [here](https://developer.android.com/jetpack/androidx/migrate) for more information.
我的项目中依赖了其他的开源库，他们有些还未升级AndroidX，所以我还不能使用AndroidX，能否出一个兼容版本可以不使用AndroidX？感谢

**Comment by Young-Joe** [comment]
> RxLifecycle 3.0.0 was pushed out to support AndroidX. If your codebase is not on AndroidX yet then you should not update.
> 
> Read up on the AndroidX migration [here](https://developer.android.com/jetpack/androidx/migrate) for more information.
> 我的项目中依赖了其他的开源库，他们有些还未升级AndroidX，所以我还不能使用AndroidX，能否出一个兼容版本可以不使用AndroidX？感谢

哈哈,你最好写英文吧. 作者估计看不懂汉语~ 我也挺想用lifecycle的.现在只能先妥协了
