### ISSUE TITLE
I can't download the 3.0.0 version

### ISSUE THREAD

**Issue by petma** [trello/RxLifecycle#295]
I want to use androidx,bug I can't download the last version,

**Comment by dlew** [comment]
What are you using to try to download it?

**Comment by petma** [comment]
> What are you using to try to download it?

implementation com.trello.rxlifecycle2:rxlifecycle:3.0.0

**Comment by petma** [comment]
> What are you using to try to download it?

I found out the reason:I used the com.trello.rxlifecycle2:rxlifecycle:3.0.0   but the right address is com.trello.rxlifecycle3:rxlifecycle:3.0.0
