### ISSUE TITLE
Does version 3.0 Fragment have to be from AndroidX？

### ISSUE THREAD

**Issue by qianshengta** [trello/RxLifecycle#298]
Does version 3.0 Fragment have to be from AndroidX？
Since my other libraries still use "support.v4", does that mean I won't be able to use version 3.0?
If version 3.0 is only available for "AndroidX", will non-androidx update?

**Comment by dlew** [comment]
The main difference between RxLifecycle 2.2.2 and RxLifecycle 3.0.0 is that 3.0.0 uses AndroidX. If you cannot use AndroidX yet, then continue to use 2.2.2.

When you are ready to update to AndroidX, you can read more on that here: https://developer.android.com/jetpack/androidx/migrate
