### ISSUE TITLE
"fragmentTransaction.add(int ,fragment)"  is wrong

### ISSUE THREAD

**Issue by huangchaoqingcheng** [trello/RxLifecycle#299]
i use rxlifecycle3.0.0  and my project use androidx ,I also add the "android.useAndroidX=true 
android.enableJetifier=true" to covert the other libraries
but when i use the code:
 supportFragmentManager.beginTransaction().add(R.id.container, fragment).commit()
it dosen't work

**Comment by dlew** [comment]
I don't see what this has to do with this library.

If you can provide a reproduction for why this library, in particular, is the cause of your problem, we can look into it.
