### ISSUE TITLE
How do I use generics in Kotlin

### ISSUE THREAD

**Issue by qianshengta** [trello/RxLifecycle#304]
![45G@}R02BN~1 JX73I LEJ2](https://user-images.githubusercontent.com/29747624/62523110-afabf280-b865-11e9-8fe9-a0fa33ab0f66.png)
In Java I don't have to pass any type, but in Kotlin I have to pass a type parameter

**Comment by dlew** [comment]
Kotlin does not allow raw types. Since it is parameterized you have to define the type. It can, however, just be `LifecycleTransformer<*>` to get the same effect as before.
