### ISSUE TITLE
Potential migrating to RxJava3

### ISSUE THREAD

**Issue by nongdenchet** [trello/RxLifecycle#315]
As RxJava3 has released for a while, do we plan to migrate to RxJava3 on a separate branch?

**Comment by dlew** [comment]
On the one hand: sure, why not. It'll probably be trivially simple to do so.

On the other hand: people really ought not to be using this library anymore - [AutoDispose](https://github.com/uber/AutoDispose) is much better and already supports RxJava 3.

I'm curious how much interest there is in continuing support - if there's enough we can bump it up.

**Comment by nongdenchet** [comment]
Thank you for your response @dlew our team is planning to upgrade to Rx3 and still have no plan migrating out of `RxLifecycle`. Let see how many people are still interested in the project.

**Comment by klamborowski** [comment]
@dlew I've made some WIP PullRequest for rxjava3 migrating :)
