### ISSUE TITLE
Usage of deprecated classes

### ISSUE THREAD

**Issue by luk-neu-tyro** [trello/RxLifecycle#328]
Some classes, e.g. _RxDialogFragment_ [1], rely on deprecated classes. 
_RxDialogFragment_ extends from _android.app.DialogFragment_, which was deprecated in API level 28 [2]. 

Have you planned to update those classes?

[1] https://github.com/trello/RxLifecycle/blob/master/rxlifecycle-components/src/main/java/com/trello/rxlifecycle4/components/RxDialogFragment.java 
[2] https://developer.android.com/reference/android/app/DialogFragment

**Comment by dlew** [comment]
What would you propose I update them to use?

**Comment by luk-neu-tyro** [comment]
I would suggest using androidx imports, like _androidx.fragment.app.DialogFragment_, instead.

What do you think about it?

Affected classes I have found by now:

com.trello.rxlifecycle4.components -> RxDialogFragment (imports android.app.DialogFragment)
com.trello.rxlifecycle4.components -> RxFragment (imports android.app.Fragment)
com.trello.rxlifecycle4.components -> RxFragmentLifecycleTest (imports android.app.Fragment)

**Comment by dlew** [comment]
Those already exist, e.g.: https://github.com/trello/RxLifecycle/blob/master/rxlifecycle-components/src/main/java/com/trello/rxlifecycle4/components/support/RxDialogFragment.java

**Comment by luk-neu-tyro** [comment]
Thank you, @dlew .
I was not aware of these classes.
