### ISSUE TITLE
Duplicate class me.tatarka.rxlifecycle_android_lifecycle_kotlin.BuildConfig

### ISSUE THREAD

**Issue by ooftf** [trello/RxLifecycle#329]
如果同时引用
rxlifecycle-android-lifecycle-kotlin   4
和
rxlifecycle-android-lifecycle-kotlin   3
就会报错
Duplicate class me.tatarka.rxlifecycle_android_lifecycle_kotlin.BuildConfig

**Comment by dlew** [comment]
I'm sorry, I don't understand. If you can provide a repro I can try to fix.

**Comment by ooftf** [comment]
https://github.com/ooftf/RxLifecycleIssues

**Comment by ooftf** [comment]
> I'm sorry, I don't understand. If you can provide a repro I can try to fix.

https://github.com/ooftf/RxLifecycleIssues

**Comment by dlew** [comment]
Aha, I see the issue. One of the package names got screwed up somehow in the rxlifecycle-android-lifecycle-kotlin manifest.

**Comment by ooftf** [comment]
> Aha, I see the issue. One of the package names got screwed up somehow in the rxlifecycle-android-lifecycle-kotlin manifest.

Will version 4.0.1 fix this issue?

**Comment by dlew** [comment]
Yup, I'll try to get that release out today.

**Comment by ooftf** [comment]
More than one file was found with OS independent path 'META-INF/rxlifecycle-android-lifecycle-kotlin_release.kotlin_module'.
new issue

**Comment by ooftf** [comment]
> More than one file was found with OS independent path 'META-INF/rxlifecycle-android-lifecycle-kotlin_release.kotlin_module'.
> new issue

kotlinOptions.freeCompilerArgs   can fix it

**Comment by dlew** [comment]
Alright, should be fixed in 4.0.2 now. I tested it on your sample project and it worked.
