### ISSUE TITLE
RxFragment should extend Fragment from androidX

### ISSUE THREAD

**Issue by iadeelzafar** [trello/RxLifecycle#334]
I use fragments from androidx library in my project. In a custom fragment when extending the `RxFragment` class, I cannot access the methods of androidx fragment class because `RxFragment` extends `android.app.Fragment` 

Can we get `RxFragment` to extend `androidx.fragment.app.Fragment`

**Comment by dlew** [comment]
This already exists in the library.

Similar question from before: https://github.com/trello/RxLifecycle/issues/328#issuecomment-700732585

**Comment by iadeelzafar** [comment]
@dlew I recently upgraded the RxLifecycle in my project from 1.0 to 4.0.2..

I'm getting this error with the `bindUntilEvent` method. I tried looking into changelogs and sample projects but couldn't find what I'm missing here. Do you have any idea how can I resolve this?

![Screenshot from 2020-11-08 18-57-56](https://user-images.githubusercontent.com/36811908/98467499-76e09300-21f7-11eb-9591-ce48f5de734a.jpg)
