### ISSUE TITLE
Specify API 23 requirement?

### ISSUE THREAD

**Issue by dkpalmer** [trello/RxLifecycle#35]
I ran into issues building against Android level 22.  Issue went away targeting API 23.  Not sure if I just missed it in the documentation or if it's worth adding to the README?

**Comment by dlew** [comment]
What issues did you run into?

**Comment by dkpalmer** [comment]
Sorry, I meant to post the error yesterday..

    [...]/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.0/res/values-v23/values-v23.xml
    Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
    Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

I see the lib uses appcompat-v7 and compiles against 23.  My app also uses appcompat-v7, but I was compiling against 22.  I'm not sure how that's resolved with Gradle.

**Comment by dlew** [comment]
It looks like the app is compiled against the highest compileSdkVersion (instead of compiling each against their own individual compileSdkVersion).

That said - there's no reason not to use the latest compileSdkVersion. minSdkVersion/targetSdkVersion have an effect on behavior but compileSdkVersion should not.

**Comment by dkpalmer** [comment]
Yeah, I've since switched both compile and target to 23.  I just hadn't done it since the official release.

**Comment by drupalmav** [comment]
Does this mean this library cannot be used with compileSdkVersion 22 & buildToolsVersion "22.0.1"?

**Comment by dlew** [comment]
No. There is no reason not to use compileSdkVersion 23 though.
