### ISSUE TITLE
min API 14 requirement?

### ISSUE THREAD

**Issue by magicgoose** [trello/RxLifecycle#36]
…/src/main/AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 10 cannot be smaller than version 14 declared in library [com.trello:rxlifecycle:0.3.0] …/build/intermediates/exploded-aar/com.trello/rxlifecycle/0.3.0/AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.trello.rxlifecycle" to force usage

Is there a real reason for this limitation?

**Comment by dlew** [comment]
The reason is because 10 is ancient and not worth supporting.
