### ISSUE TITLE
Upgrade to Fragment.onAttach(Context)

### ISSUE THREAD

**Issue by dlew** [trello/RxLifecycle#47]
API 23 introduced `Fragment.onAttach(Context)` and deprecated `Fragment.onAttach(Activity)`. We should look into using the newer version (while maintaining backwards compatibility).

**Comment by tadfisher** [comment]
Support libraries added this as well (but did not deprecate the `Activity` version)

**Comment by Deliganli** [comment]
would it be ok for me to just change onAttach(Activity) to onAttach(Context) in my RxFragment class? Because it is not receiving onAttach(Activity) lifecycle events on lower api levels.

**Comment by dlew** [comment]
I think it's fine to just depend on the back-compat call for a while.
