### ISSUE TITLE
wrong return types

### ISSUE THREAD

**Issue by shareme** [trello/RxLifecycle#49]
RxLifecyle.bindUnitEvent returns return new Observable.Transformer<T, T>

But in the components classes your are returning

Observable.Transformer<? super T, ? extends T>

on bindUntilEvent and bindToLifecycle

SO which one folks? To haphazard a guess would it be the RxLifecycle ones are correct?

**Comment by dlew** [comment]
Doesn't the whole thing use `Observable.Transformer<? super T, ? extends T>`?

You're going to have to be a bit more specific what you think is wrong.
