### ISSUE TITLE
Push snapshot version to maven

### ISSUE THREAD

**Issue by ntoskrnl** [trello/RxLifecycle#53]
Any chance the SNAPSHOT version of the library will be pushed to maven?
Since v. 0.3.0 is already released, maybe now it's time to bumb the version to 0.3.1-SNAPSHOT and push it to maven snapshot repository?

**Comment by dlew** [comment]
Is it just that you want https://github.com/trello/RxLifecycle/commit/43f052acd32ad44102e62aaf53501c2e14f8f5dd?

**Comment by ntoskrnl** [comment]
If there were no other commits, then yes))

**Comment by tadfisher** [comment]
Try https://jitpack.io/

**Comment by IgorGanapolsky** [comment]
@tadfisher What does jitpack.io solve?

**Comment by tadfisher** [comment]
If you can't wait for a fix to hit production, add a dependency that points to a commit hash on Github.

**Comment by dlew** [comment]
It's been a busy week (and now it's Thanksgiving) but I'll try to get a 0.3.1 out soon (since there is some demand for it).

**Comment by vanniktech** [comment]
+1 on 0.3.1

**Comment by dlew** [comment]
0.3.1 has been pushed to maven central; it should be out there soon.
