### ISSUE TITLE
Relax targetSdkVersion dependency 

### ISSUE THREAD

**Issue by cmathew** [trello/RxLifecycle#55]
Currently this requires SDK version 23, which is very restrictive when trying to support "older" builds of Android. Dropping this to at least 22 would allow use in Android 5 and below.

**Comment by cmathew** [comment]
@tbsandee thanks for the suggestion. If I set compileSDK to 23, but targetSDK 22, the app will behave like a 22? I ask because I'm trying to avoid the API level 23 permissions model.

**Comment by tbsandee** [comment]
Yes I'm in the same situation. Not ready to update to the new permission
model but need a few other sdk23 features. It works great for me.

**Comment by dlew** [comment]
I just took a deeper look at the code and we don't actually use `targetSdkVersion` except for the sample.

**Comment by srodenberg** [comment]
Just a note, this library depends on RxBinding which assumes View.OnScrollChangeListener exists which requires api lvl 23.
