### ISSUE TITLE
Make RxBinding dependency optional

### ISSUE THREAD

**Issue by ajalt** [trello/RxLifecycle#66]
The RxBinding library contains over 600 methods. That's about five times the total number of methods in the RxLifecycle base + components libraries. It's unfortunate that this library pulls in that many extra methods, especially when it appears that library is only used for [one line of code](https://github.com/trello/RxLifecycle/blob/master/rxlifecycle/src/main/java/com/trello/rxlifecycle/RxLifecycle.java#L154).

Would it be possible to split out the RxBinding-related functionality into an optional module?

**Comment by vanniktech** [comment]
You basically want another module e.g. rxlifecycle-view which does the complete Lifecycle View binding related stuff?

**Comment by dlew** [comment]
Alternatively, we could make RxBinding an optional dependency such that that method only works if you have actually provided RxBinding.

**Comment by dlew** [comment]
Question: How many people use RxLifecycle but not RxBinding?

**Comment by vanniktech** [comment]
I guess not that many. I do use both. So I need the dependency anyways.


On 8 December 2015 17:54:10 CET, Daniel Lew <notifications@github.com> wrote:
>Question: How many people use RxLifecycle but not RxBinding?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/trello/RxLifecycle/issues/66#issuecomment-162943580

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dlew** [comment]
I'm comfortable with depending on RxBinding for this library. If you're using this lib, you're (at least) using an `Activity` already, which implies `Views`, in which case RxBinding seems like a natural fit regardless.
