### ISSUE TITLE
How about View's lifecycle?

### ISSUE THREAD

**Issue by Piasy** [trello/RxLifecycle#72]
Could it possible to add simple View lifecycle support? e.g. `onAttachedToWindow` and `onDetachedFromWindow`.

**Comment by markrietveld** [comment]
Detach support already exists already using [this method](https://github.com/trello/RxLifecycle/blob/master/rxlifecycle/src/main/java/com/trello/rxlifecycle/RxLifecycle.java#L149) in RxLifecycle

**Comment by Piasy** [comment]
Oh yes... sorry that I miss it.

**Comment by npace** [comment]
The link provided by @markrietveld currently leads to a 404.

I think [this](https://github.com/trello/RxLifecycle/blob/1.x/rxlifecycle-android/src/main/java/com/trello/rxlifecycle/android/RxLifecycleAndroid.java#L98) is the currently valid link.
