### ISSUE TITLE
Using Observer instead of Subscriber when using RxLifecycle

### ISSUE THREAD

**Issue by ungvas** [trello/RxLifecycle#77]
Hi,

After beginning using this library i do not using any Subscriptions.

My question is:
Is ok to use Observer<T> instead of Subscriber<T> because anyway i do not use subscription functionality?

Thanks

**Comment by dlew** [comment]
Both `Observer` and `Subscriber` create subscriptions after subscribing, so the question makes no sense. RxLifecycle can be used with either.

Regardless, this is an tracker for RxLifecycle's bugs and features. If you have questions about usage please check elsewhere, like stackoverflow.com.
