### ISSUE TITLE
Failed to resolve: com.trello.rxlifecycle-kotlin:0.4.0

### ISSUE THREAD

**Issue by danijoo** [trello/RxLifecycle#90]
Hey,

Just saw the kotlin extension to this lib and wanted to give it a try. Unfortunatly I wasnt able to resolve it from either jCenter nor MavenCentral. I checked both manually and they contain every rxlifecycle package except the `-kotlin` one.

Did you forget to upload this?

Thanks, 
danijoo

**Comment by dlew** [comment]
It hasn't been uploaded yet, the docs are a bit ahead of the releases.

I'm working on getting the next update out this weekend so it'll work soon!

**Comment by danijoo** [comment]
thanks for the quick response ! :)
