### ISSUE TITLE
Experiment w/ ActivityLifecycleCallbacks

### ISSUE THREAD

**Issue by dlew** [trello/RxLifecycle#93]
Previously we avoided this route so that we could remain consistent between Activities and Fragments, but perhaps it's worth optimizing the Activity route (especially since some people just avoid Fragments altogether).

The idea is you could call `bindUntilEvent(Activity, Event)` and `bindToLifecycle(Activity)` instead of the current methods. We would then register an ActivityLifecycleCallbacks with the Application of the Activity which can provide us a lifecycle Observable.

Some questions about implementation...
- Would we create a new ActivityLifecycleCallbacks every time, or would we store a global one (or maybe one per Activity)?
- When would we unregister? Obviously we would always do so in onDestroy(), but perhaps this could be optimized (for example if you're only waiting for onPause). Generally speaking, how does the Subscriber communicate that it no longer needs the callbacks?

**Comment by hzsweers** [comment]
Could take a look at how Glide handles it: https://github.com/bumptech/glide/blob/c2fc19316d8680322cabeed31234d19e942866e8/library/src/main/java/com/bumptech/glide/manager/ActivityFragmentLifecycle.java

**Comment by dlew** [comment]
Some more recent thoughts - we could do something akin to how the Navi version of RxLifecycle works. Provide a method which turns `Activity` -> `ActivityLifecycleProvider`.

I'm still a bit stuck on the unregistering part, unless we use one global callback.

**Comment by dlew** [comment]
There are now [`FragmentLifecycleCallbacks`](https://developer.android.com/reference/android/support/v4/app/FragmentManager.FragmentLifecycleCallbacks.html) so it may be possible to look into this again.

**Comment by rusmichal** [comment]
What about `Lifecycle` components? https://developer.android.com/topic/libraries/architecture/lifecycle.html

**Comment by dlew** [comment]
Already integrated: #215
