### ISSUE TITLE
Why BehaviorSubject and not PublishSubject OR "Problems with fragment in backstack"

### ISSUE THREAD

**Issue by Den-Rimus** [trello/RxLifecycle#94]
Good day, fellow colleagues! )

We had an issue with this approach your library describes.

Imagine there is a `FragmentA` and `FragmentB`. Both subscribe to some Observable in `afterCreateView()` callback (this is our safety-callback after `onCreateView()`). Using RxLifecycle we bound this subscription until `onDestroyView()` callback.

Next: we show `FragmentA` (got our subscription bound and ready for any incoming signals), then we use Android's `FragmentManager` to navigate to `FragmentB` - using replace, but leaving `FragmentA` in backstack so we can easily navigate "back". During navigating `FragmentManager` detaches FragmentA instance and the last lifecycle event we (and, therefore, our `BehavoirSubject lifecycleSubject`) get is `FragmentEvent.DESTROY_VIEW`.

`FragmentB` also subscribes to our `Observable` and bounds to lifecycle - nothing to do here, let's go back. Since FragmentA was navigated from with backstack enabled - it's instance is still there, and last lifecycle event that lifecycleSubject got was that `FragmentEvent.DESTROY_VIEW` - he still remembers it, since that is how BehaviorSubject works and he never died because FragmentA's instance is still alive.

Getting to the point: when we resurrect `FragmentA` instance (`FragmentManager` does that for us during "back" navigation) we - as before - bind our `Observable` to lifecycle and want to subscribe to it. But the first thing we get as soon as we bind - `FragmentEvent.DESTROY_VIEW` event, out subscription immediately receives `onCompleted`. Our `FragmentA` is not happy about this - no data update is possible for him from now on.

So far we've resolved this by switching to `PublishSubject` usage in our RxBaseFragment. But I fear there is something I might have forgotten about. Can you explain why `BehaviorSubject` was used in the first place? Is our workaround applicable (assuming that none of our programmers will try to bind to observable after `onDestroyView()` callback)?

P. S.: sorry, if my explanation is too broad - Rx approach is still tricky for me and I was at the same time trying to clear things up for myself with this issue.

**Comment by dlew** [comment]
The reason `BehaviorSubject` was chosen is so that the automatic binder can figure out where (in the lifecycle) we currently are. E.g., if you're in `onCreate()`, then the library can detect that `CREATE` has been called and automatically bind until `DESTROY`.

What I don't quite understand about your scenario is the "resurrecting `FragmentA`" part. The intention is that you bind an `Observable` that is *inside* of `FragmentA` to `FragmentA`'s lifecycle. If you do it that way, then (as long as you're inside of the lifecycle) everything should work out, since (for example) the `FragmentEvent.ATTACH` should be called before anything else.

If you're trying to bind an `Observable` outside of `FragmentA` *to* `FragmentA` then you lose a lot of control over whether that makes any sense, since who knows what state `FragmentA` is in?

**Comment by Den-Rimus** [comment]
I understand about `BehaviorSubject` now, thanks.

As for `Observable`, that I'm trying to bind - it's a result of `asObservable()` called on subject that represents data stream in app-wide singletone data provider. So it is always there and multiple clients (fragments in our case) (well, technically not fragments but their presenters but that's out of current problem's scope) can bind to it to get current actual data or any updates from the same data stream.

Our problem is that our RxBaseFragment (very similar to `RxFragment` in your library) binds to lifecycle until `FragmentEvent.DESTROY_VIEW` event, then gets unsubscribed by `takeUntil` and then _the same instance_ tries to bind again, but gets `FragmentEvent.DESTROY_VIEW` event right after subscribing. Is that expected behavior?

**Comment by dlew** [comment]
When are you rebinding? It sounds like this is what's happening:

1. Fragment initialized.
1. `Fragment.onCreateView()` called.
1. Fragment subscribes to data stream, binds to its lifecycle.
1. Fragment is removed from FragmentManager.
1. `Fragment.onDestroyView()` called, which ends the data stream subscription.
1. **Fragment subscribes to data stream, binds to its lifecycle.**

It seems like there's a step missing before the bolded one - that is, `Fragment.onCreateView()` being called again.
